In [83]:
from PIL import Image
import os
import numpy as np
size = [200, 200, 3]

for f in os.listdir('.'):
    if f.endswith('.jpg'):
        i = Image.open(f)
        fn, fext = os.path.splitext(f)
        
        i.thumbnail(size)
        i.save('imagesresized/{}_crop{}'.format(fn, fext))
    
for o in os.listdir('imagesresized'):
    %matplotlib inline
    if o.endswith('.jpg'):
        print(type(im))
        #print(im.shape()
        imcrop = im[:20, :200, :200]
        print(imcrop)
        print(type(imcrop))

<class 'numpy.ndarray'>
[[[  1   2   0]
  [  1   1   3]
  [  3   3   3]
  ...
  [121 134  18]
  [139 152  36]
  [154 172  54]]

 [[ 11  11  11]
  [  7   8   2]
  [  5   6   1]
  ...
  [128 142  21]
  [141 154  36]
  [170 190  57]]

 [[ 11  12   7]
  [  8   9   1]
  [  8   8   8]
  ...
  [132 144  32]
  [128 139  34]
  [151 171  40]]

 ...

 [[  1   1   1]
  [  1   1   1]
  [  1   1   1]
  ...
  [ 99 115  17]
  [128 159  40]
  [148 182  69]]

 [[  0   0   0]
  [  1   1   1]
  [  2   2   2]
  ...
  [ 92 108  10]
  [110 140  16]
  [135 165  51]]

 [[  2   2   2]
  [  2   2   2]
  [  1   1   1]
  ...
  [ 73  80  10]
  [ 95 115  16]
  [ 95 113  31]]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[[  1   2   0]
  [  1   1   3]
  [  3   3   3]
  ...
  [121 134  18]
  [139 152  36]
  [154 172  54]]

 [[ 11  11  11]
  [  7   8   2]
  [  5   6   1]
  ...
  [128 142  21]
  [141 154  36]
  [170 190  57]]

 [[ 11  12   7]
  [  8   9   1]
  [  8   8   8]
  ...
  [132 144  32]
  [128 139  34]
  [1

In [91]:
from PIL import Image
Image.fromarray(imcrop[:70,:5464,:32],"RGB")